config/routes.rb
Rails.application.routes.draw do
  #do custom routes above
  root "sessions#home"

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  #login
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  #logout
  delete '/logout' => 'sessions#destroy'



  resources :users
  resources :bus_trips
  resources :shifts
  resources :drivers
  resources :buses
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bus.rb
class Bus < ApplicationRecord
  belongs_to :driver #current_driver
  has_many :shifts
  has_many :drivers, through: :shifts
  has_many :bus_trips, through: :shifts
end

app/models/bus_trip.rb
class BusTrip < ApplicationRecord
  belongs_to :shift
  belongs_to :user
end

app/models/driver.rb
class Driver < ApplicationRecord
    has_many :shifts
    has_many :buses, through: :shifts
    has_many :bus_trips, through: :shifts
end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :driver
  belongs_to :bus
  has_many :bus_trips
  has_many :users, through: :bus_trips
end

app/models/user.rb
class User < ApplicationRecord
    has_many :bus_trips
    has_many :shifts, through: :bus_trips
    has_secure_password #authenticate method
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    #add helper methods
    private
        def current_user
            @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id] #if there is a user id
        end

        def logged_in?
            !!session[:user_id]
        end

        def redirect_if_not_logged_in
            redirect_to '/' if !logged_in?
        end
end

app/controllers/bus_trips_controller.rb
class BusTripsController < ApplicationController
    before_action :redirect_if_not_logged_in
    def new
        # binding.pry
        @bus_trip = BusTrip.new
    end

    def create
        binding.pry
        

        @bus_trip = current_user.bus_trips.build(bus_trip_params)
        
        #add the price here instead?
        # ((params[:trip_end_time] - @bus_trip[:trip_start_time]) /60).to_i 
        if ((@bus_trip[:trip_end_time]-@bus_trip[:trip_start_time])/60).to_i <= 60
            @bus_trip[:price] = 10
        else
            @bus_trip[:price] = 50
        end
        # start_time = @bus_trip[:trip_start_time]
        # end_time = @bus_trip[:trip_end_time]
        # #CONVERSION STILL A PROBLEM
        # @bus_trip[:trip_start_time] = start_time.to_date
        # @bus_trip[:trip_end_time] = end_time.to_date
        # binding.pry

        #Update: need to add @bus_trip.shift
       if @bus_trip.save
        #redirect to show page
        redirect_to bus_trips_path
       else
        render :new
       end
      
    end

    private
    # def add_price
    #     if ((bus_trip_params[:trip_end_time]-bus_trip_params[:trip_start_time])/60).to_i <= 60
    #         bus_trip_params[:price] = 10
    #     else
    #         bus_trip_params[:price] = 50
    #     end
    # end

    

    def bus_trip_params
        params.require(:bus_trip).permit(:trip_start_time, :trip_end_time, :start_location, :end_location, :price)
        # "trip_start_time(1i)"=>"2021", "trip_start_time(2i)"=>"6", "trip_start_time(3i)"=>"15", 
        # "trip_start_time(4i)"=>"06", "trip_start_time(5i)"=>"00", "trip_end_time(1i)"=>"2021", "trip_end_time(2i)"=>"6", "trip_end_time(3i)"=>"15", "trip_end_time(4i)"=>"06", 
        # "trip_end_time(5i)"=>"30", "start_location"=>"New York", "end_location"=>"Queens"
    end

    def shift_params
        params.permit(:driver_id, :bus_id)
    end

end

app/controllers/buses_controller.rb
class BusesController < ApplicationController
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def home
    end

    def new
    end

    def create
        user = User.find_by(username: params[:user][:username])
        if user && user.authenticate(params[:user][:password])
            session[:user_id] = user.id
            redirect_to user_path(user)
        else
            flash[:message] = "Incorrect login info, please try again"
            redirect_to "/login"
        end
    
    end

    def destroy
        # binding.pry
        session.delete(:user_id)
        redirect_to root_path
    end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController

    # #add logic to this.
    # def shift
    #     # binding.pry
    #     #when a new driver is added, you can create a shift for him
    #     @shift = Shift.create()
    # end

    # private
    # def shift_params
    #     params.permit(:driver_id, :bus_id)
    # end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
    #    binding.pry
       #insert into the db
       @user = User.new(user_params)
       if @user.save
        #log them in
        session[:user_id] = @user.id
        #redirect to show page
        redirect_to @user
       else
        render :new
       end
       #user save
    end

    def show
        redirect_if_not_logged_in
        @user = User.find_by_id(params[:id])
        redirect_to '/' if !@user
    end

    private #some are permitted and some are not

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bus_trips_helper.rb
module BusTripsHelper
end

app/helpers/buses_helper.rb
module BusesHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bus_trips/index.html.erb
<h1>All Trips</h1>

app/views/bus_trips/new.html.erb
<h1>New Trip!</h1>

<%= form_for(@bus_trip) do |f| %>
    <%= f.label :trip_start_time %>
    <%= f.datetime_select :trip_start_time, :ampm => true, :minute_step => 15 %>

    <%= f.label :trip_end_time %>
    <%= f.datetime_select :trip_end_time, :ampm => true, :minute_step => 15 %>

    <%= f.label :start_location %>
    <%= f.text_field :start_location %>

    <%= f.label :end_location %>
    <%= f.text_field :end_location %>

    <%= f.submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bruber</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
    <% if logged_in? %>
    <%= link_to "Add a Trip", new_bus_trip_path %> |
    <%= link_to "All Trips", bus_trips_path %> |
    <%= link_to "Logout", logout_path, method: "delete" %>

    <% else %>
    <%= link_to "Sign Up", signup_path %>
    <%= link_to "Log In", login_path %>
    <% end %>

    </div>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up Here</h1>

<%= form_for(@user, url: '/signup' )do |f| %>

    <%= f.label :username %>
    <%= f.text_field :username %>
    <br>
    <br>
    <%= f.label :email %>
    <%= f.email_field :email, required:true%>
    <br>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password, required:true%>
    <br>
    <br>

    <%= f.submit "Submit" %>

<% end %>

app/views/users/show.html.erb
<h1>Hi, <%= @user.username %>!</h1>